CREATE TABLE [dbo].[CustomerProfileChanges] (
    [counter]               INT            IDENTITY (1, 1) NOT NULL,
    [DownloadGroup]         INT            NULL,
    [Email]                 NVARCHAR (100) NULL,
    [Phone]                 NVARCHAR (30)  NULL,
    [FullName]              NVARCHAR (250) NULL,
    [StreetAddress1]        NVARCHAR (250) NULL,
    [StreetAddress2]        NVARCHAR (250) NULL,
    [City]                  NVARCHAR (100) NULL,
    [StateProvince]         NVARCHAR (100) NULL,
    [PostalCode]            NVARCHAR (25)  NULL,
    [Island]                NVARCHAR (50)  NULL,
    [Country]               NVARCHAR (100) NULL,
    [BillingFullName]       NVARCHAR (200) NULL,
    [BillingStreetAddress1] NVARCHAR (100) NULL,
    [BillingStreetAddress2] NVARCHAR (120) NULL,
    [BillingCity]           NVARCHAR (100) NULL,
    [BillingStateProvince]  NVARCHAR (100) NULL,
    [BillingPostalCode]     NVARCHAR (25)  NULL,
    [BillingIsland]         NVARCHAR (50)  NULL,
    [BillingCountry]        NVARCHAR (100) NULL,
    [Fax]                   NVARCHAR (30)  NULL,
    [UserName]              NVARCHAR (50)  NULL,
    [Password]              NVARCHAR (50)  NULL,
    [StorePassword]         NVARCHAR (50)  NULL,
    [DateTime]              DATETIME       CONSTRAINT [DF_CustomerProfileChanges_DateTime] DEFAULT (getdate()) NULL,
    [CustomerID]            INT            NULL,
    [Phone2]                NVARCHAR (30)  NULL,
    [Phone3]                NVARCHAR (30)  NULL,
    [Email2]                NVARCHAR (100) NULL,
    [Email3]                NVARCHAR (100) NULL,
    [CustomerServerCounter] INT            NULL,
    [PowerUserName]         NVARCHAR (50)  NULL,
    [ResidentialDelivery]   NVARCHAR (15)  NULL,
    [ChargeSalesTax]        NVARCHAR (15)  NULL,
    [PriceGroup]            NVARCHAR (15)  NULL
);

