CREATE TABLE [dbo].[KirbyItemData] (
    [counter]                                   INT            IDENTITY (1, 1) NOT NULL,
    [DateTime]                                  DATETIME       CONSTRAINT [DF_KirbyItemData_DateTime] DEFAULT (getdate()) NOT NULL,
    [CDInventoryQty_Intermusic]                 INT            NOT NULL,
    [CDInventoryCost_Intermusic]                NUMERIC (9, 2) NOT NULL,
    [CDInventoryKirbysCut_Intermusic]           NUMERIC (9, 2) NOT NULL,
    [CDInventoryKirbysPercentCut_Intermusic]    NUMERIC (5, 2) NOT NULL,
    [LPInventoryQty_Intermusic]                 INT            NOT NULL,
    [LPInventoryCost_Intermusic]                NUMERIC (9, 2) NOT NULL,
    [LPInventoryKirbysCut_Intermusic]           NUMERIC (9, 2) NOT NULL,
    [LPInventoryKirbysPercentCut_Intermusic]    NUMERIC (5, 2) NOT NULL,
    [OtherInventoryQty_Intermusic]              INT            NOT NULL,
    [OtherInventoryCost_Intermusic]             NUMERIC (9, 2) NOT NULL,
    [OtherInventoryKirbysCut_Intermusic]        NUMERIC (9, 2) NOT NULL,
    [OtherInventoryKirbysPercentCut_Intermusic] NUMERIC (5, 2) NOT NULL,
    [TotalInventoryQty_Intermusic]              INT            NOT NULL,
    [TotalInventoryCost_Intermusic]             NUMERIC (9, 2) NOT NULL,
    [TotalInventoryKirbysCut_Intermusic]        NUMERIC (9, 2) NOT NULL,
    [TotalInventoryKirbysPercentCut_Intermusic] NUMERIC (5, 2) NOT NULL,
    [CD30Days_KirbysCut_Intermusic]             NUMERIC (9, 2) NOT NULL,
    [CD30Days_Cost_Intermusic]                  NUMERIC (9, 2) NOT NULL,
    [CD30Days_Quantity_Intermusic]              INT            NOT NULL,
    [LP30Days_KirbysCut_Intermusic]             NUMERIC (9, 2) NOT NULL,
    [LP30Days_Cost_Intermusic]                  NUMERIC (9, 2) NOT NULL,
    [LP30Days_Quantity_Intermusic]              INT            NOT NULL,
    [Other30Days_KirbysCut_Intermusic]          NUMERIC (9, 2) NOT NULL,
    [Other30Days_Cost_Intermusic]               NUMERIC (9, 2) NOT NULL,
    [Other30Days_Quantity_Intermusic]           INT            NOT NULL,
    [Total30Days_KirbysCut_Intermusic]          NUMERIC (9, 2) NOT NULL,
    [Total30Days_Cost_Intermusic]               NUMERIC (9, 2) NOT NULL,
    [Total30Days_Quantity_Intermusic]           INT            NOT NULL,
    [CDInventoryQty]                            INT            NOT NULL,
    [CDInventoryCost]                           NUMERIC (9, 2) NOT NULL,
    [CDInventoryKirbysCut]                      NUMERIC (9, 2) NOT NULL,
    [CDInventoryKirbysPercentCut]               NUMERIC (5, 2) NOT NULL,
    [LPInventoryQty]                            INT            NOT NULL,
    [LPInventoryCost]                           NUMERIC (9, 2) NOT NULL,
    [LPInventoryKirbysCut]                      NUMERIC (9, 2) NOT NULL,
    [LPInventoryKirbysPercentCut]               NUMERIC (5, 2) NOT NULL,
    [OtherInventoryQty]                         INT            NOT NULL,
    [OtherInventoryCost]                        NUMERIC (9, 2) NOT NULL,
    [OtherInventoryKirbysCut]                   NUMERIC (9, 2) NOT NULL,
    [OtherInventoryKirbysPercentCut]            NUMERIC (5, 2) NOT NULL,
    [TotalInventoryQty]                         INT            NOT NULL,
    [TotalInventoryCost]                        NUMERIC (9, 2) NOT NULL,
    [TotalInventoryKirbysCut]                   NUMERIC (9, 2) NOT NULL,
    [TotalInventoryKirbysPercentCut]            NUMERIC (5, 2) NOT NULL,
    [CD30Days_KirbysCut]                        NUMERIC (9, 2) NOT NULL,
    [CD30Days_Cost]                             NUMERIC (9, 2) NOT NULL,
    [CD30Days_Quantity]                         INT            NOT NULL,
    [LP30Days_KirbysCut]                        NUMERIC (9, 2) NOT NULL,
    [LP30Days_Cost]                             NUMERIC (9, 2) NOT NULL,
    [LP30Days_Quantity]                         INT            NOT NULL,
    [Other30Days_KirbysCut]                     NUMERIC (9, 2) NOT NULL,
    [Other30Days_Cost]                          NUMERIC (9, 2) NOT NULL,
    [Other30Days_Quantity]                      INT            NOT NULL,
    [Total30Days_KirbysCut]                     NUMERIC (9, 2) NOT NULL,
    [Total30Days_Cost]                          NUMERIC (9, 2) NOT NULL,
    [Total30Days_Quantity]                      INT            NOT NULL,
    [CD30Days_KirbysCut_Intermusic_FSI]         NUMERIC (9, 2) NOT NULL,
    [CD30Days_Cost_Intermusic_FSI]              NUMERIC (9, 2) NOT NULL,
    [CD30Days_Quantity_Intermusic_FSI]          INT            NOT NULL,
    [LP30Days_KirbysCut_Intermusic_FSI]         NUMERIC (9, 2) NOT NULL,
    [LP30Days_Cost_Intermusic_FSI]              NUMERIC (9, 2) NOT NULL,
    [LP30Days_Quantity_Intermusic_FSI]          INT            NOT NULL,
    [Other30Days_KirbysCut_Intermusic_FSI]      NUMERIC (9, 2) NOT NULL,
    [Other30Days_Cost_Intermusic_FSI]           NUMERIC (9, 2) NOT NULL,
    [Other30Days_Quantity_Intermusic_FSI]       INT            NOT NULL,
    [Total30Days_KirbysCut_Intermusic_FSI]      NUMERIC (9, 2) NOT NULL,
    [Total30Days_Cost_Intermusic_FSI]           NUMERIC (9, 2) NOT NULL,
    [Total30Days_Quantity_Intermusic_FSI]       INT            NOT NULL,
    [CD30Days_KirbysCut_FSI]                    NUMERIC (9, 2) NOT NULL,
    [CD30Days_Cost_FSI]                         NUMERIC (9, 2) NOT NULL,
    [CD30Days_Quantity_FSI]                     INT            NOT NULL,
    [LP30Days_KirbysCut_FSI]                    NUMERIC (9, 2) NOT NULL,
    [LP30Days_Cost_FSI]                         NUMERIC (9, 2) NOT NULL,
    [LP30Days_Quantity_FSI]                     INT            NOT NULL,
    [Other30Days_KirbysCut_FSI]                 NUMERIC (9, 2) NOT NULL,
    [Other30Days_Cost_FSI]                      NUMERIC (9, 2) NOT NULL,
    [Other30Days_Quantity_FSI]                  INT            NOT NULL,
    [Total30Days_KirbysCut_FSI]                 NUMERIC (9, 2) NOT NULL,
    [Total30Days_Cost_FSI]                      NUMERIC (9, 2) NOT NULL,
    [Total30Days_Quantity_FSI]                  INT            NOT NULL,
    [SoldItemsTableDaysBehind]                  INT            NOT NULL,
    CONSTRAINT [PK_KirbyItemData] PRIMARY KEY CLUSTERED ([counter] ASC)
);

