CREATE TABLE [dbo].[SearchCriteriaStatistics] (
    [DateTime]              SMALLDATETIME  CONSTRAINT [DF_SearchCriteriaStatistics_2_DateTime] DEFAULT (getdate()) NULL,
    [PowerUserName]         NVARCHAR (10)  NULL,
    [IPAddress]             NVARCHAR (50)  NULL,
    [SessionID]             NVARCHAR (50)  NULL,
    [UserAgentString]       NVARCHAR (200) NULL,
    [QueryType]             NVARCHAR (50)  NULL,
    [ArtistTitle]           NVARCHAR (50)  NULL,
    [Format]                NVARCHAR (10)  NULL,
    [HowRecent]             SMALLINT       NULL,
    [YearRange]             NVARCHAR (20)  NULL,
    [PriceRange]            NVARCHAR (20)  NULL,
    [Genre]                 NVARCHAR (30)  NULL,
    [Label]                 NVARCHAR (120) NULL,
    [NewOrUsed]             NVARCHAR (10)  NULL,
    [SortOrder]             NVARCHAR (20)  NULL,
    [NumberOfRecords]       INT            NULL,
    [PageOn]                SMALLINT       NULL,
    [DisplayType]           NVARCHAR (15)  NULL,
    [ArtistSelected]        NVARCHAR (100) NULL,
    [LabelSelected]         NVARCHAR (100) NULL,
    [GenreSelected]         NVARCHAR (30)  NULL,
    [SearchTypeDescription] NVARCHAR (255) NULL,
    [SearchID]              NVARCHAR (50)  NULL,
    [CustomerID]            NVARCHAR (50)  CONSTRAINT [DF_SearchCriteriaStatistics_2_CustomerID] DEFAULT ('-') NULL,
    [CustomerServerCounter] INT            NULL,
    [AllArtist]             NVARCHAR (100) NULL,
    [AllLabel]              NVARCHAR (100) NULL,
    [AllRhythm]             NVARCHAR (100) NULL,
    [AllGenre]              NVARCHAR (100) NULL,
    [counter]               INT            IDENTITY (1, 1) NOT NULL,
    [HTTP_REFERER]          NVARCHAR (300) NULL,
    [REMOTE_HOST]           NVARCHAR (300) NULL,
    [ButtonColor]           NVARCHAR (15)  NULL,
    [FromOurSite]           NVARCHAR (1)   NULL
);

