CREATE TABLE [dbo].[WebCountryShippingZonesT] (
    [ID]                                        INT            NOT NULL,
    [Country]                                   NVARCHAR (100) NULL,
    [FedExInternationalPriorityZone]            NVARCHAR (15)  NULL,
    [AirParcelPostZone]                         NVARCHAR (15)  NULL,
    [AirSmallPacketZone]                        NVARCHAR (15)  NULL,
    [ErnieShippingZone]                         NVARCHAR (5)   NULL,
    [LetterPostRateGroup]                       NVARCHAR (50)  NULL,
    [GlobalExpressZone]                         NVARCHAR (50)  NULL,
    [FedExInternationalEconomyZone]             NVARCHAR (15)  NULL,
    [FedexExportRatesThatWeChargeCustomersZone] NVARCHAR (15)  NULL,
    [EuropeanUnionCountry]                      NVARCHAR (1)   NULL,
    [AirSmallPacketWeightLimit]                 INT            NULL,
    [RetailMinimumShippingCharge]               MONEY          NULL,
    [RetailPercentShippingCharge]               FLOAT (53)     NULL,
    [FedExCountryCode]                          NVARCHAR (2)   NULL,
    [PostalCodeRequired]                        NVARCHAR (1)   NULL,
    [StateProvinceRequired]                     NVARCHAR (1)   NULL,
    [StateProvinceWord]                         NVARCHAR (50)  NULL,
    [AddressUpperCase]                          NVARCHAR (1)   NULL,
    [AddressCityLine1]                          NVARCHAR (50)  NULL,
    [AddressCityLine2]                          NVARCHAR (50)  NULL,
    [CityRequired]                              NVARCHAR (1)   NULL,
    [IslandRequired]                            NVARCHAR (1)   NULL,
    [IslandWord]                                NVARCHAR (50)  NULL,
    [CityWord]                                  NVARCHAR (50)  NULL,
    [PostalCodeWord]                            NVARCHAR (50)  NULL,
    [PostalCodeFormat]                          NVARCHAR (50)  NULL,
    [FedExFranceIPDZone]                        NVARCHAR (50)  NULL,
    [DutyShippingCostPercent]                   FLOAT (53)     NULL,
    [EconomySurfaceParcelPostZone]              NVARCHAR (2)   NULL,
    [WebUSMailWholesaleAllowed]                 NVARCHAR (1)   NULL,
    [FedexPhoneNumber]                          NVARCHAR (50)  NULL,
    [AirParcelPostWeightLimit]                  INT            NULL,
    [GlobalExpressWeightLimit]                  INT            NULL,
    [AllowFedexInternationalPriorityForRetail]  NVARCHAR (50)  NULL,
    [AutomaticUSMailInsurance]                  NVARCHAR (50)  NULL,
    [DHLFlatRate]                               DECIMAL (8, 2) NOT NULL,
    [DHLInternationalExpressZone]               NVARCHAR (2)   NOT NULL
);

