CREATE TABLE [dbo].[WebSHIPX_ShippingMethods] (
    [ShippingMethodCode]                     NVARCHAR (50)  NULL,
    [Domestic]                               NVARCHAR (1)   NULL,
    [International]                          NVARCHAR (1)   NULL,
    [USPossessions]                          NVARCHAR (1)   NULL,
    [PickUpTime]                             DATETIME       NULL,
    [ShipViaService]                         NVARCHAR (50)  NULL,
    [ShippingViaCompany]                     NVARCHAR (50)  NULL,
    [ShippingCostTableName]                  NVARCHAR (80)  NULL,
    [POBoxOK]                                NVARCHAR (1)   NULL,
    [CODOK]                                  NVARCHAR (1)   NULL,
    [FuelSurcharge]                          FLOAT (53)     NULL,
    [OurDutyCostPercent]                     FLOAT (53)     NULL,
    [MaxWeightOfShipment]                    INT            NULL,
    [MaxWeightOfBox]                         INT            NULL,
    [ShipmentFlatRateWeight]                 INT            NULL,
    [CODCharge]                              MONEY          NULL,
    [ResidentialDeliveryCharge]              MONEY          NULL,
    [MilitaryAddressOK]                      NVARCHAR (1)   NULL,
    [DeliveryDateGuaranteed]                 NVARCHAR (1)   NULL,
    [EUCountries]                            NVARCHAR (1)   NULL,
    [NumberOfBoxesMatters]                   NVARCHAR (1)   NULL,
    [MinimumWeightOfShipment]                INT            NULL,
    [HolidayColumnName]                      NVARCHAR (50)  NULL,
    [SaturdayDeliveryCharge]                 MONEY          NULL,
    [WebShippingCutoffMinutes]               INT            NULL,
    [OfficeShippingCutoffMinutes]            INT            NULL,
    [PullSheetText]                          NVARCHAR (50)  NULL,
    [Hawaii]                                 NVARCHAR (1)   NULL,
    [Alaska]                                 NVARCHAR (1)   NULL,
    [Description1]                           NVARCHAR (MAX) NULL,
    [Description2]                           NVARCHAR (MAX) NULL,
    [Description3]                           NVARCHAR (MAX) NULL,
    [Description4]                           NVARCHAR (MAX) NULL,
    [TrackingWord]                           NVARCHAR (MAX) NULL,
    [WebsiteTrackingDescription1]            NVARCHAR (MAX) NULL,
    [WebsiteTrackingDescription2]            NVARCHAR (MAX) NULL,
    [WebsiteTrackingDescription3]            NVARCHAR (MAX) NULL,
    [WebsiteTrackingDescription4]            NVARCHAR (MAX) NULL,
    [LPor12InchSurcharge]                    MONEY          NOT NULL,
    [CustomFlatShippingChargeSpendThreshold] MONEY          NULL,
    [CustomFlatShippingCharge]               MONEY          NULL,
    [counter]                                INT            NOT NULL,
    [FedExAPIServiceEnumeration]             NVARCHAR (50)  NULL,
    CONSTRAINT [PK_WebSHIPX_ShippingMethods] PRIMARY KEY CLUSTERED ([counter] ASC)
);

