// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MillionsOfRecordsApp.Models;

[Index("CartName", Name = "IX_CartName")]
[Index("CartName", "ItemId", Name = "IX_CartNameItemID", IsUnique = true)]
[Index("SaveForLater", Name = "IX_SaveForLater")]
[Index("SubtractedInventory", Name = "IX_SubtractedInventory")]
public partial class Cart
{
    [Required]
    [StringLength(60)]
    public string CartName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateTime { get; set; }

    [Column("ItemID")]
    public int ItemId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal Price { get; set; }

    [Key]
    [Column("counter")]
    public int Counter { get; set; }

    [Column("IPAddress")]
    [StringLength(20)]
    public string Ipaddress { get; set; }

    [Column("SearchCriteriaStatisticsID")]
    [StringLength(50)]
    public string SearchCriteriaStatisticsId { get; set; }

    [StringLength(15)]
    public string OrderNumber { get; set; }

    [StringLength(1)]
    public string SubtractedInventory { get; set; }

    [StringLength(1)]
    public string SaveForLater { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string InSync { get; set; }
}