// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MillionsOfRecordsApp.Models;

[Keyless]
[Table("CountryList")]
public partial class CountryList
{
    [Column("counter")]
    public int Counter { get; set; }

    [StringLength(100)]
    public string CountryText { get; set; }

    [StringLength(100)]
    public string Country { get; set; }

    [StringLength(100)]
    public string StateProvince { get; set; }

    [StringLength(100)]
    public string SortOrderText { get; set; }

    [StringLength(100)]
    public string City { get; set; }
}