// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MillionsOfRecordsApp.Models;

[Keyless]
[Index("CartQuantity", Name = "IX_CartQuantity")]
[Index("CustomerId", Name = "IX_CustomerID")]
[Index("DateOfLastCartAdjustment", Name = "IX_DateOfLastCartAdjustment")]
[Index("DateOfLastLogin", Name = "IX_DateOfLastLogin")]
[Index("DateOfLastOrder", Name = "IX_DateOfLastOrder")]
[Index("LogInEmail", Name = "IX_LogInEmail", IsUnique = true)]
[Index("LogInEmail", "Password", Name = "IX_LogInEmailPassword", IsUnique = true)]
[Index("PowerUserName", Name = "IX_PowerUserName")]
[Index("SuperPowerUserName", Name = "IX_SuperPowerUserName")]
[Index("Counter", Name = "IX_counter")]
public partial class Customer
{
    [StringLength(50)]
    public string UserName { get; set; }

    [StringLength(50)]
    public string Password { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(30)]
    public string Phone { get; set; }

    [StringLength(120)]
    public string FullName { get; set; }

    [StringLength(100)]
    public string StreetAddress1 { get; set; }

    [StringLength(100)]
    public string StreetAddress2 { get; set; }

    [StringLength(100)]
    public string City { get; set; }

    [StringLength(100)]
    public string StateProvince { get; set; }

    [StringLength(25)]
    public string PostalCode { get; set; }

    [StringLength(50)]
    public string Island { get; set; }

    [StringLength(50)]
    public string Country { get; set; }

    [StringLength(120)]
    public string BillingFullName { get; set; }

    [StringLength(100)]
    public string BillingStreetAddress1 { get; set; }

    [StringLength(100)]
    public string BillingStreetAddress2 { get; set; }

    [StringLength(100)]
    public string BillingCity { get; set; }

    [StringLength(100)]
    public string BillingStateProvince { get; set; }

    [StringLength(25)]
    public string BillingPostalCode { get; set; }

    [StringLength(50)]
    public string BillingIsland { get; set; }

    [StringLength(50)]
    public string BillingCountry { get; set; }

    [StringLength(300)]
    public string Address1 { get; set; }

    [StringLength(300)]
    public string Address2 { get; set; }

    [StringLength(300)]
    public string Address3 { get; set; }

    [StringLength(300)]
    public string Address4 { get; set; }

    [Column("USPossession")]
    [StringLength(100)]
    public string Uspossession { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DateTime { get; set; }

    [StringLength(10)]
    public string CaTax { get; set; }

    [StringLength(30)]
    public string CreditApprovalCode { get; set; }

    [Column("counter")]
    public int Counter { get; set; }

    [StringLength(50)]
    public string HowFoundUs { get; set; }

    [Column("CustomerID")]
    [StringLength(50)]
    public string CustomerId { get; set; }

    [StringLength(30)]
    public string Phone2 { get; set; }

    [StringLength(30)]
    public string Phone3 { get; set; }

    [StringLength(100)]
    public string Email2 { get; set; }

    [StringLength(100)]
    public string Email3 { get; set; }

    [StringLength(30)]
    public string Fax { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfLastOrder { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfLastLogin { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfLastCustomerInteraction { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfLastCartAdjustment { get; set; }

    [StringLength(100)]
    public string LogInEmail { get; set; }

    [StringLength(50)]
    public string PriceGroup { get; set; }

    [StringLength(50)]
    public string Attn { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal? MinimumOrder { get; set; }

    [StringLength(20)]
    public string PowerUserName { get; set; }

    [StringLength(50)]
    public string SuperPowerUserName { get; set; }

    [StringLength(1)]
    public string ResidentialDelivery { get; set; }

    [StringLength(1)]
    public string ChargeSalesTax { get; set; }

    [Column("IPAddress")]
    [StringLength(50)]
    public string Ipaddress { get; set; }

    [Column("counterOLD")]
    public int? CounterOld { get; set; }

    public int? CartQuantity { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string InSync { get; set; }

    public int TotalSignIns { get; set; }

    [Column(TypeName = "numeric(8, 2)")]
    public decimal CurrentCartTotalPrice { get; set; }

    public int? NumberOfCartReminderEmailsSent { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfLastCartReminderEmailSent { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfLastSearch { get; set; }

    [StringLength(1)]
    public string BlockedFromCheckout { get; set; }

    [Column("EmailedNWEB")]
    [StringLength(10)]
    public string EmailedNweb { get; set; }
}