// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MillionsOfRecordsApp.Models;

[Keyless]
public partial class DatabaseVariable
{
    [StringLength(1)]
    public string SearchCriteriaDownloads { get; set; }

    [StringLength(1)]
    public string DownloadOrders { get; set; }

    [Column("IsINTERNETREGGAEMaintenanceOpen")]
    [StringLength(50)]
    public string IsInternetreggaemaintenanceOpen { get; set; }

    [StringLength(1)]
    public string OrdersToTag { get; set; }

    [StringLength(1)]
    public string AddToCart { get; set; }

    [StringLength(1)]
    public string UploadPhotos { get; set; }

    [StringLength(1)]
    public string FigureWebSearchSuggestions { get; set; }
}