// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MillionsOfRecordsApp.Models;

[Keyless]
[Table("Inventory")]
[Index("ArtistTitle", Name = "IX_ArtistTitle")]
[Index("Genre1", Name = "IX_Genre1")]
[Index("Genre2", Name = "IX_Genre2")]
[Index("Genre3", Name = "IX_Genre3")]
[Index("Genre4", Name = "IX_Genre4")]
[Index("Genre5", Name = "IX_Genre5")]
[Index("Genre6", Name = "IX_Genre6")]
[Index("Genre7", Name = "IX_Genre7")]
[Index("Genre8", Name = "IX_Genre8")]
[Index("Genre9", Name = "IX_Genre9")]
[Index("Id", Name = "IX_ID", IsUnique = true)]
[Index("Inventory1", Name = "IX_Inventory")]
[Index("Format", "UsedItem", "ShowOnWebsite", "Id", "Inventory1", Name = "IX_OPT1")]
[Index("Format", "UsedItem", "ShowOnWebsite", "Id", "Inventory1", Name = "IX_OPT2")]
[Index("RhythmName", Name = "IX_RhythmName")]
[Index("YearFrom", Name = "IX_YearFrom")]
[Index("YearTo", Name = "IX_YearTo")]
[Index("BackInStockDate", Name = "ix_BackInStockDate")]
[Index("FormatOrder", Name = "ix_FormatOrder")]
[Index("InStockDate", Name = "ix_InStockDate")]
[Index("SalesLast30Days", Name = "ix_SalesLast30Days")]
public partial class Inventory
{
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(350)]
    public string ArtistTitle { get; set; }

    [Required]
    [StringLength(120)]
    public string Label { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal RetailPrice { get; set; }

    [Column("Inventory")]
    public int Inventory1 { get; set; }

    [Required]
    [StringLength(7)]
    public string Format { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InStockDate { get; set; }

    [StringLength(400)]
    public string RhythmName { get; set; }

    [StringLength(30)]
    public string YearFrom { get; set; }

    [StringLength(30)]
    public string YearTo { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal StorePrice { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime BackInStockDate { get; set; }

    public string ProduceGroup { get; set; }

    public string MusicianGroup { get; set; }

    public string TracksGroup { get; set; }

    [StringLength(50)]
    public string Catalog { get; set; }

    public int? SalesLast30Days { get; set; }

    public int FormatOrder { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal? ExportPrice { get; set; }

    [StringLength(1)]
    public string WebEssential { get; set; }

    [Column("WebReviewHTML")]
    public string WebReviewHtml { get; set; }

    [StringLength(1)]
    public string Cutout { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal WeightInGrams { get; set; }

    public int? NumberOfTracks { get; set; }

    [StringLength(1)]
    public string Deleted { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal Cost { get; set; }

    [Column("MP3FileCompleted")]
    [StringLength(1)]
    public string Mp3fileCompleted { get; set; }

    [StringLength(1)]
    public string UsedItem { get; set; }

    [StringLength(3)]
    public string ConditionJacket { get; set; }

    [Column("ConditionVinylOrCD")]
    [StringLength(3)]
    public string ConditionVinylOrCd { get; set; }

    [Column("MP3SoundGroup")]
    public int? Mp3soundGroup { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateAdded { get; set; }

    [StringLength(30)]
    public string Genre1 { get; set; }

    [StringLength(30)]
    public string Genre2 { get; set; }

    [StringLength(30)]
    public string Genre3 { get; set; }

    [StringLength(30)]
    public string Genre4 { get; set; }

    [StringLength(30)]
    public string Genre5 { get; set; }

    [StringLength(30)]
    public string Genre6 { get; set; }

    [StringLength(30)]
    public string Genre7 { get; set; }

    [StringLength(30)]
    public string Genre8 { get; set; }

    [StringLength(30)]
    public string Genre9 { get; set; }

    [Column("UPC")]
    [StringLength(50)]
    public string Upc { get; set; }

    [StringLength(100)]
    public string ItemDetailsWeb { get; set; }

    [StringLength(255)]
    public string ItemDetailsWebProductDetails { get; set; }

    [Column("Sale_RetailPrice", TypeName = "numeric(5, 2)")]
    public decimal? SaleRetailPrice { get; set; }

    [Column("Sale_RetailEndDate", TypeName = "datetime")]
    public DateTime? SaleRetailEndDate { get; set; }

    [Column("Sale_RetailFootnoteText")]
    [StringLength(255)]
    public string SaleRetailFootnoteText { get; set; }

    [Column("Sale_RetailItemDetailsText")]
    [StringLength(255)]
    public string SaleRetailItemDetailsText { get; set; }

    [Column("Sale_WholesalePrice", TypeName = "numeric(5, 2)")]
    public decimal? SaleWholesalePrice { get; set; }

    [Column("Sale_WholesaleEndDate", TypeName = "datetime")]
    public DateTime? SaleWholesaleEndDate { get; set; }

    [Column("Sale_WholesaleFootnoteText")]
    [StringLength(255)]
    public string SaleWholesaleFootnoteText { get; set; }

    [Column("Sale_WholesaleItemDetailsText")]
    [StringLength(255)]
    public string SaleWholesaleItemDetailsText { get; set; }

    [StringLength(255)]
    public string ItemFootnoteText { get; set; }

    [Column("SupplierID")]
    public int SupplierId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StreetDate { get; set; }

    [StringLength(1)]
    public string ShowOnWebsite { get; set; }

    public string ConditionNotes { get; set; }

    public string ConditionText { get; set; }

    public string ItemFeatures1 { get; set; }

    public string ItemFeatures2 { get; set; }

    public string ItemFeatures3 { get; set; }

    public string ItemFeatures4 { get; set; }

    public string ItemFeatures5 { get; set; }

    public string ItemFeatures6 { get; set; }

    public string ItemFeatures7 { get; set; }

    public string ItemFeatures8 { get; set; }

    public string ItemFeatures9 { get; set; }

    public string ItemFeatures10 { get; set; }

    [Column(TypeName = "numeric(6, 2)")]
    public decimal KirbysCut { get; set; }

    [Required]
    [StringLength(1)]
    public string KirbyItem { get; set; }

    [Column(TypeName = "numeric(6, 2)")]
    public decimal KirbyCost { get; set; }
}