// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MillionsOfRecordsApp.Models;

[Table("InventoryItemFeatureIndex")]
public partial class InventoryItemFeatureIndex
{
    [Key]
    [Column("InventoryItemFeatureID")]
    public int InventoryItemFeatureId { get; set; }

    [StringLength(255)]
    public string DescriptionForInternalUse { get; set; }

    [StringLength(25)]
    public string FormatText { get; set; }

    [StringLength(10)]
    public string FormatForInternalUse { get; set; }

    [StringLength(100)]
    public string ItemFeatureWebGalleryText { get; set; }

    public int? ItemFeatureWebGalleryTextDisplaySequence { get; set; }

    [StringLength(255)]
    public string ItemFeatureHoverOverText { get; set; }

    [StringLength(255)]
    public string ItemFeatureWebProductDetailsPageText { get; set; }

    public int? ItemFeatureWebProductDetailsPageTextDisplaySequence { get; set; }

    public string ItemFeatureWebProductDetailsPageHyperlinkText { get; set; }

    [StringLength(255)]
    public string ItemFeaturesOrderAndInvoicePagesText { get; set; }

    public int? ItemFeaturesOrderAndInvoicePagesTextDisplaySequence { get; set; }

    [StringLength(255)]
    public string ItemFeatureExcelFileText { get; set; }

    public int? ItemFeatureExcelFileTextDisplaySequence { get; set; }

    [Column("EBrecordsInventoryItemFeatureID")]
    public int? EbrecordsInventoryItemFeatureId { get; set; }

    [Column("counter")]
    public int? Counter { get; set; }

    [StringLength(255)]
    public string Hint { get; set; }
}