// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MillionsOfRecordsApp.Models;

[Keyless]
[Index("InventoryItemFeatureId", Name = "IX_InventoryItemFeatureID_ItemID")]
[Index("ItemId", Name = "IX_ItemID")]
public partial class InventoryItemFeature
{
    [Column("ID")]
    public int Id { get; set; }

    [Column("InventoryItemFeatureID")]
    public int InventoryItemFeatureId { get; set; }

    [Column("ItemID")]
    public int ItemId { get; set; }
}