// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spCartPricesSalePricesTooResult
    {
        public int CartCounter { get; set; }
        public decimal Price { get; set; }
        public int ItemID { get; set; }
        public decimal RetailPrice { get; set; }
        public decimal StorePrice { get; set; }
        public decimal? ExportPrice { get; set; }
        [Column("Sale_RetailPrice", TypeName = "decimal(5,2)")]
        public decimal? Sale_RetailPrice { get; set; }
        public DateTime? Sale_RetailEndDate { get; set; }
        [Column("Sale_WholesalePrice", TypeName = "decimal(5,2)")]
        public decimal? Sale_WholesalePrice { get; set; }
        public DateTime? Sale_WholesaleEndDate { get; set; }
    }
}
