// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spCheckLogInEmailExistsResult
    {
        public int counter { get; set; }
        [StringLength(50)]
        public string PriceGroup { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [StringLength(120)]
        public string FullName { get; set; }
    }
}
