// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spDownload_CustomerEmailChangesResult
    {
        public DateTime DateTime { get; set; }
        public int CustomerID { get; set; }
        public int CustomerServerCounter { get; set; }
        [StringLength(100)]
        public string OldEmail { get; set; }
        [StringLength(100)]
        public string NewEmail { get; set; }
        public int? DownloadGroup { get; set; }
        public int counter { get; set; }
    }
}
