// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spDownload_SignInLogResult
    {
        public DateTime? DateTime { get; set; }
        [StringLength(50)]
        public string IPAddress { get; set; }
        [StringLength(3)]
        public string LoggedOnSuccessful { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [StringLength(150)]
        public string StoreName { get; set; }
        [StringLength(100)]
        public string City { get; set; }
        public int Counter { get; set; }
        [StringLength(20)]
        public string PriceGroup { get; set; }
        [StringLength(50)]
        public string PowerUserName { get; set; }
        public int? CustomerServerCounter { get; set; }
        [StringLength(100)]
        public string LogInEmail { get; set; }
        public int? CartQuantity { get; set; }
        public string InSync { get; set; }
    }
}
