// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spDownload_OrderItemsResult
    {
        public int? InventoryID { get; set; }
        public decimal? Price { get; set; }
        public int? Quantity { get; set; }
        public int counter { get; set; }
        public int? Inventory { get; set; }
        [StringLength(50)]
        public string SearchCriteriaStatisticsID { get; set; }
    }
}
