// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spDownload_Enter7InchResult
    {
        public int Quantity { get; set; }
        [StringLength(200)]
        public string SideATrack1 { get; set; }
        [StringLength(150)]
        public string SideBTrack1 { get; set; }
        [StringLength(120)]
        public string Label { get; set; }
        [StringLength(30)]
        public string Year { get; set; }
        [StringLength(30)]
        public string Genre1 { get; set; }
        [StringLength(30)]
        public string Genre2 { get; set; }
        [StringLength(30)]
        public string Genre3 { get; set; }
        [StringLength(100)]
        public string Description1 { get; set; }
        [StringLength(250)]
        public string Description2 { get; set; }
        [StringLength(350)]
        public string FullDescription { get; set; }
        public int counter { get; set; }
        [StringLength(100)]
        public string Worker { get; set; }
        public int WorkerID { get; set; }
        [StringLength(50)]
        public string Batch { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [StringLength(50)]
        public string RandomNumberID { get; set; }
        public DateTime DateTime { get; set; }
        public int? WallID { get; set; }
        [StringLength(5)]
        public string WallCatalogLetter { get; set; }
        public int? WallCatalogNumber { get; set; }
        [StringLength(400)]
        public string RhythmName { get; set; }
    }
}
