// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spDownload_OrderCorrectionNotesResult
    {
        public int counter { get; set; }
        [StringLength(50)]
        public string OrderNumber { get; set; }
        [StringLength(150)]
        public string Email { get; set; }
        public int? PrintGroup { get; set; }
        [StringLength(300)]
        public string CustomerName { get; set; }
        [StringLength(100)]
        public string LogInEmail { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [StringLength(5000)]
        public string CorrectionNote { get; set; }
        public DateTime? DateTimeNote { get; set; }
        [StringLength(50)]
        public string CustomerID { get; set; }
        public DateTime? DateTimeOrdered { get; set; }
        public int? DownloadGroup { get; set; }
        public int? CustomerServerCounter { get; set; }
    }
}
