// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spDownload_DeleteBackordersInStockNowResult
    {
        public int? CustomerID { get; set; }
        public int? DeleteBackorderInventoryID { get; set; }
        public int? DownloadGroup { get; set; }
        public int counter { get; set; }
        [StringLength(1)]
        public string AddedToCart { get; set; }
        public DateTime? DateTime { get; set; }
    }
}
