// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spDownload_EnterStockResult
    {
        public int counter { get; set; }
        [StringLength(50)]
        public string UPC { get; set; }
        [StringLength(150)]
        public string Artist { get; set; }
        [StringLength(150)]
        public string Title { get; set; }
        [StringLength(130)]
        public string Label { get; set; }
        [StringLength(30)]
        public string Genre1 { get; set; }
        [StringLength(30)]
        public string Genre2 { get; set; }
        [StringLength(30)]
        public string Genre3 { get; set; }
        [StringLength(50)]
        public string Catalog { get; set; }
        [StringLength(5)]
        public string WallCatalogLetter { get; set; }
        public int? WallCatalogNumber { get; set; }
        public int Quantity { get; set; }
        [Column("Price", TypeName = "decimal(10,2)")]
        public decimal? Price { get; set; }
        [StringLength(1)]
        public string UsedItem { get; set; }
        [StringLength(7)]
        public string Format { get; set; }
        [StringLength(100)]
        public string Worker { get; set; }
        public int WorkerID { get; set; }
        public int Batch { get; set; }
        public DateTime DateTime { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [StringLength(50)]
        public string RandomNumberID { get; set; }
        public int? WallID { get; set; }
    }
}
