// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spDownload_PayFlowRequestsResult
    {
        public int counter { get; set; }
        [StringLength(50)]
        public string Status { get; set; }
        [StringLength(300)]
        public string UserAgent { get; set; }
        [StringLength(1)]
        public string Request_TRXTYPE { get; set; }
        [StringLength(1)]
        public string Request_TENDER { get; set; }
        [StringLength(6)]
        public string Request_EXPDATE { get; set; }
        [Column("REQUEST_Amt", TypeName = "decimal(9,2)")]
        public decimal? REQUEST_Amt { get; set; }
        [StringLength(30)]
        public string Request_BILLTOFIRSTNAME { get; set; }
        [StringLength(30)]
        public string Request_BILLTOLASTNAME { get; set; }
        [StringLength(30)]
        public string Request_BILLTOSTREET { get; set; }
        [StringLength(30)]
        public string Request_BILLTOSTREET2 { get; set; }
        [StringLength(20)]
        public string Request_BILLTOCITY { get; set; }
        [StringLength(2)]
        public string Request_BILLTOSTATE { get; set; }
        [StringLength(9)]
        public string Request_BILLTOZIP { get; set; }
        [StringLength(3)]
        public string Request_BILLTOCOUNTRY { get; set; }
        [StringLength(20)]
        public string Request_CUSTIP { get; set; }
        [StringLength(100)]
        public string Request_ORDERID { get; set; }
        [StringLength(128)]
        public string Request_COMMENT1 { get; set; }
        [StringLength(128)]
        public string Request_COMMENT2 { get; set; }
        [StringLength(20)]
        public string Response_PNREF { get; set; }
        [StringLength(25)]
        public string Response_PPREF { get; set; }
        public int? Response_RESULT { get; set; }
        [StringLength(1)]
        public string Response_CVV2MATCH { get; set; }
        [StringLength(2147483647)]
        public string Response_RESPMSG { get; set; }
        public short? Response_DUPLICATE { get; set; }
        [StringLength(10)]
        public string Response_PROCAVS { get; set; }
        [StringLength(20)]
        public string WebOrderNumber { get; set; }
        public int? CustomerID { get; set; }
        [StringLength(10)]
        public string VBNETPostType { get; set; }
        public DateTime? DateTime { get; set; }
        [StringLength(4)]
        public string RightFour { get; set; }
    }
}
