// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spDownload_PayPalIPNsReceivedResult
    {
        [StringLength(200)]
        public string ReceiverEmail { get; set; }
        [StringLength(50)]
        public string ReceiverID { get; set; }
        [StringLength(255)]
        public string WebOrderNumber { get; set; }
        public DateTime? DateTime { get; set; }
        public double? PaymentGross { get; set; }
        [StringLength(50)]
        public string PaymentStatus { get; set; }
        [StringLength(50)]
        public string PendingReason { get; set; }
        [StringLength(50)]
        public string ReasonCode { get; set; }
        public int counter { get; set; }
        [StringLength(50)]
        public string PaypalTransactionID { get; set; }
        [StringLength(50)]
        public string ParentPaypalTransactionID { get; set; }
        [StringLength(50)]
        public string PaymentType { get; set; }
        public double? PaymentFee { get; set; }
        public int? CustomerID { get; set; }
        [StringLength(150)]
        public string PayPalEmail { get; set; }
        [StringLength(50)]
        public string Category { get; set; }
        [StringLength(255)]
        public string Note { get; set; }
        public int? DownloadGroup { get; set; }
        [StringLength(50)]
        public string PaymentCurrency { get; set; }
        [StringLength(70)]
        public string FirstName { get; set; }
        [StringLength(70)]
        public string LastName { get; set; }
        [StringLength(130)]
        public string BusinessName { get; set; }
        [StringLength(20)]
        public string PayPalID { get; set; }
    }
}
