// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spForgotPasswordResult
    {
        [StringLength(120)]
        public string Fullname { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        [StringLength(100)]
        public string LogInEmail { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        public int counter { get; set; }
    }
}
