// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetCartTotalsRetailPriceResult
    {
        public int? Quantity { get; set; }
        public DateTime? DateTime { get; set; }
        public int? datedifference { get; set; }
        public decimal? Price { get; set; }
        public decimal? PriceForCart { get; set; }
        public decimal RetailPrice { get; set; }
        [StringLength(7)]
        public string Format { get; set; }
    }
}
