// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetWeightOfProductResult
    {
        [Column("sumweight", TypeName = "decimal(38,0)")]
        public decimal sumweight { get; set; }
    }
}
