// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetMinimumFlatShippngChargeResult
    {
        [StringLength(50)]
        public string ShippingMethodCode { get; set; }
        [StringLength(1)]
        public string Domestic { get; set; }
        [StringLength(1)]
        public string International { get; set; }
        [StringLength(1)]
        public string USPossessions { get; set; }
        public DateTime? PickUpTime { get; set; }
        [StringLength(50)]
        public string ShipViaService { get; set; }
        [StringLength(50)]
        public string ShippingViaCompany { get; set; }
        [StringLength(80)]
        public string ShippingCostTableName { get; set; }
        [StringLength(1)]
        public string POBoxOK { get; set; }
        [StringLength(1)]
        public string CODOK { get; set; }
        public double? FuelSurcharge { get; set; }
        public double? OurDutyCostPercent { get; set; }
        public int? MaxWeightOfShipment { get; set; }
        public int? MaxWeightOfBox { get; set; }
        public int? ShipmentFlatRateWeight { get; set; }
        [Column("CODCharge", TypeName = "money")]
        public decimal? CODCharge { get; set; }
        [Column("ResidentialDeliveryCharge", TypeName = "money")]
        public decimal? ResidentialDeliveryCharge { get; set; }
        [StringLength(1)]
        public string MilitaryAddressOK { get; set; }
        [StringLength(1)]
        public string DeliveryDateGuaranteed { get; set; }
        [StringLength(1)]
        public string EUCountries { get; set; }
        [StringLength(1)]
        public string NumberOfBoxesMatters { get; set; }
        public int? MinimumWeightOfShipment { get; set; }
        [StringLength(50)]
        public string HolidayColumnName { get; set; }
        [Column("SaturdayDeliveryCharge", TypeName = "money")]
        public decimal? SaturdayDeliveryCharge { get; set; }
        public int? WebShippingCutoffMinutes { get; set; }
        public int? OfficeShippingCutoffMinutes { get; set; }
        [StringLength(50)]
        public string PullSheetText { get; set; }
        [StringLength(1)]
        public string Hawaii { get; set; }
        [StringLength(1)]
        public string Alaska { get; set; }
        [StringLength(2147483647)]
        public string Description1 { get; set; }
        [StringLength(2147483647)]
        public string Description2 { get; set; }
        [StringLength(2147483647)]
        public string Description3 { get; set; }
        [StringLength(2147483647)]
        public string Description4 { get; set; }
        [StringLength(2147483647)]
        public string TrackingWord { get; set; }
        [StringLength(2147483647)]
        public string WebsiteTrackingDescription1 { get; set; }
        [StringLength(2147483647)]
        public string WebsiteTrackingDescription2 { get; set; }
        [StringLength(2147483647)]
        public string WebsiteTrackingDescription3 { get; set; }
        [StringLength(2147483647)]
        public string WebsiteTrackingDescription4 { get; set; }
        [Column("LPor12InchSurcharge", TypeName = "money")]
        public decimal LPor12InchSurcharge { get; set; }
        [Column("CustomFlatShippingChargeSpendThreshold", TypeName = "money")]
        public decimal? CustomFlatShippingChargeSpendThreshold { get; set; }
        [Column("CustomFlatShippingCharge", TypeName = "money")]
        public decimal? CustomFlatShippingCharge { get; set; }
        public int counter { get; set; }
        [StringLength(50)]
        public string FedExAPIServiceEnumeration { get; set; }
    }
}
