// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetWebSHIPX_ShippingHolidaysOutboundRowResult
    {
        public DateTime? Date { get; set; }
        [StringLength(1)]
        public string FedexAirHoliday { get; set; }
        [StringLength(1)]
        public string FedexGroundHoliday { get; set; }
        [StringLength(1)]
        public string USPSHoliday { get; set; }
        [StringLength(1)]
        public string WorkHoliday { get; set; }
        [StringLength(1)]
        public string UPSGroundHoliday { get; set; }
        public int counter { get; set; }
    }
}
