// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetTermsOfSaleTypesRowResult
    {
        public int? Type { get; set; }
        public int counter { get; set; }
        [StringLength(100)]
        public string TextOnInvoice { get; set; }
        [StringLength(100)]
        public string TextOnWebsitePaymentButton { get; set; }
        public int? DaysUntilDue { get; set; }
        public string RetailUSA { get; set; }
        public string RetailInternational { get; set; }
        public string WholesaleUSA { get; set; }
        public string WholesaleInternational { get; set; }
        public int? TermsDays { get; set; }
    }
}
