// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetOrdersByCustomerServerCounterResult
    {
        [StringLength(20)]
        public string Status { get; set; }
        [StringLength(100)]
        public string LogInEmail { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        [StringLength(30)]
        public string Phone { get; set; }
        [StringLength(150)]
        public string FullName { get; set; }
        [StringLength(150)]
        public string StreetAddress1 { get; set; }
        [StringLength(150)]
        public string StreetAddress2 { get; set; }
        [StringLength(100)]
        public string City { get; set; }
        [StringLength(100)]
        public string StateProvince { get; set; }
        [StringLength(25)]
        public string PostalCode { get; set; }
        [StringLength(50)]
        public string Island { get; set; }
        [StringLength(100)]
        public string Country { get; set; }
        [StringLength(200)]
        public string BillingFullName { get; set; }
        [StringLength(100)]
        public string BillingStreetAddress1 { get; set; }
        [StringLength(120)]
        public string BillingStreetAddress2 { get; set; }
        [StringLength(100)]
        public string BillingCity { get; set; }
        [StringLength(100)]
        public string BillingStateProvince { get; set; }
        [StringLength(25)]
        public string BillingPostalCode { get; set; }
        [StringLength(50)]
        public string BillingIsland { get; set; }
        [StringLength(100)]
        public string BillingCountry { get; set; }
        [StringLength(100)]
        public string USPossession { get; set; }
        public DateTime? DateTime { get; set; }
        [StringLength(50)]
        public string ShippingMethod { get; set; }
        [StringLength(255)]
        public string CreditCardNumber { get; set; }
        [StringLength(6)]
        public string ExpDate { get; set; }
        [Column("CreditCardAmountPaid", TypeName = "decimal(10,2)")]
        public decimal? CreditCardAmountPaid { get; set; }
        [StringLength(15)]
        public string OrderNumber { get; set; }
        [Column("Shipping", TypeName = "decimal(7,2)")]
        public decimal? Shipping { get; set; }
        [Column("Tax", TypeName = "decimal(7,2)")]
        public decimal? Tax { get; set; }
        [StringLength(50)]
        public string IPAddress { get; set; }
        [StringLength(50)]
        public string Browser { get; set; }
        [StringLength(50)]
        public string BrowserVersion { get; set; }
        [StringLength(50)]
        public string Platform { get; set; }
        [StringLength(50)]
        public string StorePassword { get; set; }
        [StringLength(2147483647)]
        public string OrderNotes { get; set; }
        [StringLength(50)]
        public string OrderProcessChoice { get; set; }
        [StringLength(50)]
        public string Fax { get; set; }
        [StringLength(50)]
        public string Attn { get; set; }
        [StringLength(2147483647)]
        public string ChangedAddress { get; set; }
        [StringLength(400)]
        public string RemHost { get; set; }
        [StringLength(100)]
        public string PONumber { get; set; }
        public int counter { get; set; }
        [StringLength(50)]
        public string PowerUserName { get; set; }
        [StringLength(30)]
        public string CustomerID { get; set; }
        [StringLength(10)]
        public string PowerUserNewCustomer { get; set; }
        public decimal? Cost { get; set; }
        [StringLength(50)]
        public string HowFoundUs { get; set; }
        [Column("PaypalAmountDue", TypeName = "decimal(10,2)")]
        public decimal? PaypalAmountDue { get; set; }
        [StringLength(50)]
        public string PaypalTransactionID { get; set; }
        [StringLength(50)]
        public string PaypalPaymentStatus { get; set; }
        [StringLength(50)]
        public string PayPalPendingReason { get; set; }
        [Column("PayPalAmountPaid", TypeName = "decimal(10,2)")]
        public decimal? PayPalAmountPaid { get; set; }
        [StringLength(100)]
        public string PayPalEmail { get; set; }
        [StringLength(50)]
        public string ShippingMethodPullSheetText { get; set; }
        [Column("Weight", TypeName = "decimal(10,2)")]
        public decimal? Weight { get; set; }
        [Column("WesternUnionAmountDue", TypeName = "decimal(10,2)")]
        public decimal? WesternUnionAmountDue { get; set; }
        [Column("CheckCashorMoneyOrderAmountDue", TypeName = "decimal(10,2)")]
        public decimal? CheckCashorMoneyOrderAmountDue { get; set; }
        [Column("OrderTotal", TypeName = "decimal(10,2)")]
        public decimal? OrderTotal { get; set; }
        [StringLength(50)]
        public string SessionID { get; set; }
        [StringLength(50)]
        public string PaymentsProTransactionID { get; set; }
        [StringLength(30)]
        public string Phone2 { get; set; }
        [StringLength(30)]
        public string Phone3 { get; set; }
        [StringLength(100)]
        public string Email2 { get; set; }
        [StringLength(100)]
        public string Email3 { get; set; }
        public int? CustomerServerCounter { get; set; }
        public int? InvoiceNumber { get; set; }
        [Column("GiftCardAmount", TypeName = "decimal(10,2)")]
        public decimal? GiftCardAmount { get; set; }
        [StringLength(20)]
        public string GiftCardNumber { get; set; }
        public int? GiftCardAccountsServerCounter { get; set; }
        [StringLength(2147483647)]
        public string UserAgent { get; set; }
        public int? NumberOfLineItems { get; set; }
        [StringLength(20)]
        public string PriceGroup { get; set; }
        public int? DownloadGroup { get; set; }
        [StringLength(10)]
        public string EmailedConfirmation { get; set; }
        public int? TotalQuantity { get; set; }
        [Column("TotalPrice", TypeName = "decimal(8,2)")]
        public decimal? TotalPrice { get; set; }
        [StringLength(1)]
        public string EmailedToInquireIfPayPalOrderProblem { get; set; }
        [Column("GoogleCheckoutAmountDue", TypeName = "decimal(18,2)")]
        public decimal? GoogleCheckoutAmountDue { get; set; }
        [Column("GoogleCheckoutAmountPaid", TypeName = "decimal(18,2)")]
        public decimal? GoogleCheckoutAmountPaid { get; set; }
        [StringLength(1)]
        public string PrintedInvoice { get; set; }
        [StringLength(10)]
        public string EmailedOWEB { get; set; }
    }
}
