// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetAirMailLetterPostZoneResult
    {
        public int ID { get; set; }
        [StringLength(100)]
        public string Country { get; set; }
        [StringLength(15)]
        public string FedExInternationalPriorityZone { get; set; }
        [StringLength(15)]
        public string AirParcelPostZone { get; set; }
        [StringLength(15)]
        public string AirSmallPacketZone { get; set; }
        [StringLength(5)]
        public string ErnieShippingZone { get; set; }
        [StringLength(50)]
        public string LetterPostRateGroup { get; set; }
        [StringLength(50)]
        public string GlobalExpressZone { get; set; }
        [StringLength(15)]
        public string FedExInternationalEconomyZone { get; set; }
        [StringLength(15)]
        public string FedexExportRatesThatWeChargeCustomersZone { get; set; }
        [StringLength(1)]
        public string EuropeanUnionCountry { get; set; }
        public int? AirSmallPacketWeightLimit { get; set; }
        [Column("RetailMinimumShippingCharge", TypeName = "money")]
        public decimal? RetailMinimumShippingCharge { get; set; }
        public double? RetailPercentShippingCharge { get; set; }
        [StringLength(2)]
        public string FedExCountryCode { get; set; }
        [StringLength(1)]
        public string PostalCodeRequired { get; set; }
        [StringLength(1)]
        public string StateProvinceRequired { get; set; }
        [StringLength(50)]
        public string StateProvinceWord { get; set; }
        [StringLength(1)]
        public string AddressUpperCase { get; set; }
        [StringLength(50)]
        public string AddressCityLine1 { get; set; }
        [StringLength(50)]
        public string AddressCityLine2 { get; set; }
        [StringLength(1)]
        public string CityRequired { get; set; }
        [StringLength(1)]
        public string IslandRequired { get; set; }
        [StringLength(50)]
        public string IslandWord { get; set; }
        [StringLength(50)]
        public string CityWord { get; set; }
        [StringLength(50)]
        public string PostalCodeWord { get; set; }
        [StringLength(50)]
        public string PostalCodeFormat { get; set; }
        [StringLength(50)]
        public string FedExFranceIPDZone { get; set; }
        public double? DutyShippingCostPercent { get; set; }
        [StringLength(2)]
        public string EconomySurfaceParcelPostZone { get; set; }
        [StringLength(1)]
        public string WebUSMailWholesaleAllowed { get; set; }
        [StringLength(50)]
        public string FedexPhoneNumber { get; set; }
        public int? AirParcelPostWeightLimit { get; set; }
        public int? GlobalExpressWeightLimit { get; set; }
        [StringLength(50)]
        public string AllowFedexInternationalPriorityForRetail { get; set; }
        [StringLength(50)]
        public string AutomaticUSMailInsurance { get; set; }
        [Column("DHLFlatRate", TypeName = "decimal(8,2)")]
        public decimal DHLFlatRate { get; set; }
        [StringLength(2)]
        public string DHLInternationalExpressZone { get; set; }
    }
}
