// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetKirbysCutThisMonthResult
    {
        [StringLength(20)]
        public string ThisMonth6PercentCut { get; set; }
        [StringLength(20)]
        public string ThisMonthKirbyItemCut { get; set; }
        [StringLength(20)]
        public string ThisMonthKirbyCapDealCut { get; set; }
    }
}
