// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetKirbysCutTodayResult
    {
        [StringLength(20)]
        public string Today6PercentCut { get; set; }
        [StringLength(20)]
        public string TodayKirbyItemCut { get; set; }
        [StringLength(20)]
        public string TodayKirbyCapDealCut { get; set; }
    }
}
