// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetCartItemsResult
    {
        [StringLength(60)]
        public string CartName { get; set; }
        public DateTime DateTime { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int counter { get; set; }
        [StringLength(20)]
        public string IPAddress { get; set; }
        [StringLength(50)]
        public string SearchCriteriaStatisticsID { get; set; }
        [StringLength(15)]
        public string OrderNumber { get; set; }
        [StringLength(1)]
        public string SubtractedInventory { get; set; }
        [StringLength(1)]
        public string SaveForLater { get; set; }
        public string InSync { get; set; }
    }
}
