// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetCustomerDetailsResult
    {
        [StringLength(50)]
        public string UserName { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        [StringLength(30)]
        public string Phone { get; set; }
        [StringLength(120)]
        public string FullName { get; set; }
        [StringLength(100)]
        public string StreetAddress1 { get; set; }
        [StringLength(100)]
        public string StreetAddress2 { get; set; }
        [StringLength(100)]
        public string City { get; set; }
        [StringLength(100)]
        public string StateProvince { get; set; }
        [StringLength(25)]
        public string PostalCode { get; set; }
        [StringLength(50)]
        public string Island { get; set; }
        [StringLength(50)]
        public string Country { get; set; }
        [StringLength(120)]
        public string BillingFullName { get; set; }
        [StringLength(100)]
        public string BillingStreetAddress1 { get; set; }
        [StringLength(100)]
        public string BillingStreetAddress2 { get; set; }
        [StringLength(100)]
        public string BillingCity { get; set; }
        [StringLength(100)]
        public string BillingStateProvince { get; set; }
        [StringLength(25)]
        public string BillingPostalCode { get; set; }
        [StringLength(50)]
        public string BillingIsland { get; set; }
        [StringLength(50)]
        public string BillingCountry { get; set; }
        [StringLength(300)]
        public string Address1 { get; set; }
        [StringLength(300)]
        public string Address2 { get; set; }
        [StringLength(300)]
        public string Address3 { get; set; }
        [StringLength(300)]
        public string Address4 { get; set; }
        [StringLength(100)]
        public string USPossession { get; set; }
        public string DateTime { get; set; }
        [StringLength(10)]
        public string CaTax { get; set; }
        [StringLength(30)]
        public string CreditApprovalCode { get; set; }
        public int counter { get; set; }
        [StringLength(50)]
        public string HowFoundUs { get; set; }
        [StringLength(50)]
        public string CustomerID { get; set; }
        [StringLength(30)]
        public string Phone2 { get; set; }
        [StringLength(30)]
        public string Phone3 { get; set; }
        [StringLength(100)]
        public string Email2 { get; set; }
        [StringLength(100)]
        public string Email3 { get; set; }
        [StringLength(30)]
        public string Fax { get; set; }
        public DateTime? DateOfLastOrder { get; set; }
        public DateTime? DateOfLastLogin { get; set; }
        public DateTime? DateOfLastCustomerInteraction { get; set; }
        public DateTime? DateOfLastCartAdjustment { get; set; }
        [StringLength(100)]
        public string LogInEmail { get; set; }
        [StringLength(50)]
        public string PriceGroup { get; set; }
        [StringLength(50)]
        public string Attn { get; set; }
        public decimal? MinimumOrder { get; set; }
        [StringLength(20)]
        public string PowerUserName { get; set; }
        [StringLength(50)]
        public string SuperPowerUserName { get; set; }
        [StringLength(1)]
        public string ResidentialDelivery { get; set; }
        [StringLength(1)]
        public string ChargeSalesTax { get; set; }
        [StringLength(50)]
        public string IPAddress { get; set; }
        public int? counterOLD { get; set; }
        public int? CartQuantity { get; set; }
        public string InSync { get; set; }
        public int TotalSignIns { get; set; }
        [Column("CurrentCartTotalPrice", TypeName = "decimal(8,2)")]
        public decimal CurrentCartTotalPrice { get; set; }
        public int? NumberOfCartReminderEmailsSent { get; set; }
        public DateTime? DateOfLastCartReminderEmailSent { get; set; }
        public DateTime? DateOfLastSearch { get; set; }
        [StringLength(1)]
        public string BlockedFromCheckout { get; set; }
        [StringLength(10)]
        public string EmailedNWEB { get; set; }
    }
}
