// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetOrderItemsResult
    {
        [StringLength(15)]
        public string OrderNumber { get; set; }
        public int? InventoryID { get; set; }
        public decimal? Price { get; set; }
        public int? Quantity { get; set; }
        public int? Inventory { get; set; }
        [StringLength(50)]
        public string SearchCriteriaStatisticsID { get; set; }
        [StringLength(200)]
        public string Label { get; set; }
        [StringLength(10)]
        public string Format { get; set; }
        [StringLength(30)]
        public string Catalog { get; set; }
        public int counter { get; set; }
        [StringLength(350)]
        public string Description { get; set; }
        public int? DownloadGroup { get; set; }
        public DateTime? OrderItemsDateTime { get; set; }
        [Column("KirbysCut", TypeName = "decimal(6,2)")]
        public decimal? KirbysCut { get; set; }
        [StringLength(1)]
        public string KirbyItem { get; set; }
        public int? SupplierID { get; set; }
        public decimal? Cost { get; set; }
        [Column("KirbyCost", TypeName = "decimal(6,2)")]
        public decimal KirbyCost { get; set; }
    }
}
