// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetWebSHIPX_UPSTimeInTransitRowResult
    {
        [StringLength(5)]
        public string ZipCode { get; set; }
        public int? Days { get; set; }
    }
}
