// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetCustomerInvoicesResult
    {
        public int CustID { get; set; }
        public DateTime InvoiceDate { get; set; }
        public int InvoiceNumber { get; set; }
        public DateTime ShipDate { get; set; }
        [StringLength(2147483647)]
        public string TrackingNumber { get; set; }
        [StringLength(40)]
        public string ShippingCompany { get; set; }
        [StringLength(50)]
        public string ShippingServiceName { get; set; }
        [Column("InvoiceTotal", TypeName = "decimal(8,2)")]
        public decimal InvoiceTotal { get; set; }
        [StringLength(2147483647)]
        public string WebOrderNumbers { get; set; }
        public int CustomerServerCounter { get; set; }
        [StringLength(55)]
        public string PDFFileName { get; set; }
        public int counter { get; set; }
    }
}
