// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetInventoryItemResult
    {
        public int ID { get; set; }
        [StringLength(350)]
        public string ArtistTitle { get; set; }
        [StringLength(120)]
        public string Label { get; set; }
        public decimal RetailPrice { get; set; }
        public int Inventory { get; set; }
        [StringLength(7)]
        public string Format { get; set; }
        public DateTime InStockDate { get; set; }
        [StringLength(400)]
        public string RhythmName { get; set; }
        [StringLength(30)]
        public string YearFrom { get; set; }
        [StringLength(30)]
        public string YearTo { get; set; }
        public decimal StorePrice { get; set; }
        public DateTime BackInStockDate { get; set; }
        [StringLength(2147483647)]
        public string ProduceGroup { get; set; }
        [StringLength(2147483647)]
        public string MusicianGroup { get; set; }
        [StringLength(2147483647)]
        public string TracksGroup { get; set; }
        [StringLength(50)]
        public string Catalog { get; set; }
        public int? SalesLast30Days { get; set; }
        public int FormatOrder { get; set; }
        public decimal? ExportPrice { get; set; }
        [StringLength(1)]
        public string WebEssential { get; set; }
        [StringLength(2147483647)]
        public string WebReviewHTML { get; set; }
        [StringLength(1)]
        public string Cutout { get; set; }
        [Column("WeightInGrams", TypeName = "decimal(18,0)")]
        public decimal WeightInGrams { get; set; }
        public int? NumberOfTracks { get; set; }
        [StringLength(1)]
        public string Deleted { get; set; }
        public decimal Cost { get; set; }
        [StringLength(1)]
        public string MP3FileCompleted { get; set; }
        [StringLength(1)]
        public string UsedItem { get; set; }
        [StringLength(3)]
        public string ConditionJacket { get; set; }
        [StringLength(3)]
        public string ConditionVinylOrCD { get; set; }
        public int? MP3SoundGroup { get; set; }
        public DateTime? DateAdded { get; set; }
        [StringLength(30)]
        public string Genre1 { get; set; }
        [StringLength(30)]
        public string Genre2 { get; set; }
        [StringLength(30)]
        public string Genre3 { get; set; }
        [StringLength(30)]
        public string Genre4 { get; set; }
        [StringLength(30)]
        public string Genre5 { get; set; }
        [StringLength(30)]
        public string Genre6 { get; set; }
        [StringLength(30)]
        public string Genre7 { get; set; }
        [StringLength(30)]
        public string Genre8 { get; set; }
        [StringLength(30)]
        public string Genre9 { get; set; }
        [StringLength(50)]
        public string UPC { get; set; }
        [StringLength(100)]
        public string ItemDetailsWeb { get; set; }
        [StringLength(255)]
        public string ItemDetailsWebProductDetails { get; set; }
        [Column("Sale_RetailPrice", TypeName = "decimal(5,2)")]
        public decimal? Sale_RetailPrice { get; set; }
        public DateTime? Sale_RetailEndDate { get; set; }
        [StringLength(255)]
        public string Sale_RetailFootnoteText { get; set; }
        [StringLength(255)]
        public string Sale_RetailItemDetailsText { get; set; }
        [Column("Sale_WholesalePrice", TypeName = "decimal(5,2)")]
        public decimal? Sale_WholesalePrice { get; set; }
        public DateTime? Sale_WholesaleEndDate { get; set; }
        [StringLength(255)]
        public string Sale_WholesaleFootnoteText { get; set; }
        [StringLength(255)]
        public string Sale_WholesaleItemDetailsText { get; set; }
        [StringLength(255)]
        public string ItemFootnoteText { get; set; }
        public int SupplierID { get; set; }
        public DateTime? StreetDate { get; set; }
        [StringLength(1)]
        public string ShowOnWebsite { get; set; }
        [StringLength(2147483647)]
        public string ConditionNotes { get; set; }
        [StringLength(2147483647)]
        public string ConditionText { get; set; }
        [StringLength(2147483647)]
        public string ItemFeatures1 { get; set; }
        [StringLength(2147483647)]
        public string ItemFeatures2 { get; set; }
        [StringLength(2147483647)]
        public string ItemFeatures3 { get; set; }
        [StringLength(2147483647)]
        public string ItemFeatures4 { get; set; }
        [StringLength(2147483647)]
        public string ItemFeatures5 { get; set; }
        [StringLength(2147483647)]
        public string ItemFeatures6 { get; set; }
        [StringLength(2147483647)]
        public string ItemFeatures7 { get; set; }
        [StringLength(2147483647)]
        public string ItemFeatures8 { get; set; }
        [StringLength(2147483647)]
        public string ItemFeatures9 { get; set; }
        [StringLength(2147483647)]
        public string ItemFeatures10 { get; set; }
        [Column("KirbysCut", TypeName = "decimal(6,2)")]
        public decimal KirbysCut { get; set; }
        [StringLength(1)]
        public string KirbyItem { get; set; }
        [Column("KirbyCost", TypeName = "decimal(6,2)")]
        public decimal KirbyCost { get; set; }
    }
}
