// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetEmailFooterResult
    {
        [StringLength(2147483647)]
        public string Footer { get; set; }
        public int counter { get; set; }
    }
}
