// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spGetWebCountryStateProvincesListRowResult
    {
        [StringLength(100)]
        public string Country { get; set; }
        [StringLength(100)]
        public string StateProvince { get; set; }
        [StringLength(50)]
        public string StateProvinceAbbreviation { get; set; }
        public int? counter { get; set; }
    }
}
