// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spHTTPDownloadDataOrderItemsResult
    {
        public int? InventoryID { get; set; }
        public decimal? Price { get; set; }
        public int? Quantity { get; set; }
        public int counter { get; set; }
        public int? Inventory { get; set; }
        [StringLength(50)]
        public string SearchCriteriaStatisticsID { get; set; }
        public int? SupplierID { get; set; }
        [StringLength(1)]
        public string KirbyItem { get; set; }
        [Column("KirbysCut", TypeName = "decimal(6,2)")]
        public decimal? KirbysCut { get; set; }
        public decimal? Cost { get; set; }
        [Column("KirbyCost", TypeName = "decimal(6,2)")]
        public decimal KirbyCost { get; set; }
    }
}
