// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spInventoryItemFeaturesForProductDetailsPageResult
    {
        public int InventoryItemFeatureID { get; set; }
        [StringLength(255)]
        public string DescriptionForInternalUse { get; set; }
        [StringLength(25)]
        public string FormatText { get; set; }
        [StringLength(10)]
        public string FormatForInternalUse { get; set; }
        [StringLength(100)]
        public string ItemFeatureWebGalleryText { get; set; }
        public int? ItemFeatureWebGalleryTextDisplaySequence { get; set; }
        [StringLength(255)]
        public string ItemFeatureHoverOverText { get; set; }
        [StringLength(255)]
        public string ItemFeatureWebProductDetailsPageText { get; set; }
        public int? ItemFeatureWebProductDetailsPageTextDisplaySequence { get; set; }
        [StringLength(2147483647)]
        public string ItemFeatureWebProductDetailsPageHyperlinkText { get; set; }
        [StringLength(255)]
        public string ItemFeaturesOrderAndInvoicePagesText { get; set; }
        public int? ItemFeaturesOrderAndInvoicePagesTextDisplaySequence { get; set; }
        [StringLength(255)]
        public string ItemFeatureExcelFileText { get; set; }
        public int? ItemFeatureExcelFileTextDisplaySequence { get; set; }
        public int? EBrecordsInventoryItemFeatureID { get; set; }
        public int? counter { get; set; }
        [StringLength(255)]
        public string Hint { get; set; }
    }
}
