// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spKirbyItemDataResult
    {
        public int BoughtHistory { get; set; }
        public int SoldHistory { get; set; }
        public int CDInventoryQty_Intermusic { get; set; }
        [Column("CDInventoryCost_Intermusic", TypeName = "decimal(9,2)")]
        public decimal CDInventoryCost_Intermusic { get; set; }
        [Column("CDInventoryKirbysCut_Intermusic", TypeName = "decimal(9,2)")]
        public decimal CDInventoryKirbysCut_Intermusic { get; set; }
        [Column("CDInventoryKirbysPercentCut_Intermusic", TypeName = "decimal(5,2)")]
        public decimal CDInventoryKirbysPercentCut_Intermusic { get; set; }
        public int LPInventoryQty_Intermusic { get; set; }
        [Column("LPInventoryCost_Intermusic", TypeName = "decimal(9,2)")]
        public decimal LPInventoryCost_Intermusic { get; set; }
        [Column("LPInventoryKirbysCut_Intermusic", TypeName = "decimal(9,2)")]
        public decimal LPInventoryKirbysCut_Intermusic { get; set; }
        [Column("LPInventoryKirbysPercentCut_Intermusic", TypeName = "decimal(5,2)")]
        public decimal LPInventoryKirbysPercentCut_Intermusic { get; set; }
        public int OtherInventoryQty_Intermusic { get; set; }
        [Column("OtherInventoryCost_Intermusic", TypeName = "decimal(9,2)")]
        public decimal OtherInventoryCost_Intermusic { get; set; }
        [Column("OtherInventoryKirbysCut_Intermusic", TypeName = "decimal(9,2)")]
        public decimal OtherInventoryKirbysCut_Intermusic { get; set; }
        [Column("OtherInventoryKirbysPercentCut_Intermusic", TypeName = "decimal(5,2)")]
        public decimal OtherInventoryKirbysPercentCut_Intermusic { get; set; }
        public int TotalInventoryQty_Intermusic { get; set; }
        [Column("TotalInventoryCost_Intermusic", TypeName = "decimal(9,2)")]
        public decimal TotalInventoryCost_Intermusic { get; set; }
        [Column("TotalInventoryKirbysCut_Intermusic", TypeName = "decimal(9,2)")]
        public decimal TotalInventoryKirbysCut_Intermusic { get; set; }
        [Column("TotalInventoryKirbysPercentCut_Intermusic", TypeName = "decimal(5,2)")]
        public decimal TotalInventoryKirbysPercentCut_Intermusic { get; set; }
        [Column("CD30Days_KirbysCut_Intermusic", TypeName = "decimal(9,2)")]
        public decimal CD30Days_KirbysCut_Intermusic { get; set; }
        [Column("CD30Days_Cost_Intermusic", TypeName = "decimal(9,2)")]
        public decimal CD30Days_Cost_Intermusic { get; set; }
        public int CD30Days_Quantity_Intermusic { get; set; }
        [Column("LP30Days_KirbysCut_Intermusic", TypeName = "decimal(9,2)")]
        public decimal LP30Days_KirbysCut_Intermusic { get; set; }
        [Column("LP30Days_Cost_Intermusic", TypeName = "decimal(9,2)")]
        public decimal LP30Days_Cost_Intermusic { get; set; }
        public int LP30Days_Quantity_Intermusic { get; set; }
        [Column("Other30Days_KirbysCut_Intermusic", TypeName = "decimal(9,2)")]
        public decimal Other30Days_KirbysCut_Intermusic { get; set; }
        [Column("Other30Days_Cost_Intermusic", TypeName = "decimal(9,2)")]
        public decimal Other30Days_Cost_Intermusic { get; set; }
        public int Other30Days_Quantity_Intermusic { get; set; }
        [Column("Total30Days_KirbysCut_Intermusic", TypeName = "decimal(9,2)")]
        public decimal Total30Days_KirbysCut_Intermusic { get; set; }
        [Column("Total30Days_Cost_Intermusic", TypeName = "decimal(9,2)")]
        public decimal Total30Days_Cost_Intermusic { get; set; }
        public int Total30Days_Quantity_Intermusic { get; set; }
        public int CDInventoryQty { get; set; }
        [Column("CDInventoryCost", TypeName = "decimal(9,2)")]
        public decimal CDInventoryCost { get; set; }
        [Column("CDInventoryKirbysCut", TypeName = "decimal(9,2)")]
        public decimal CDInventoryKirbysCut { get; set; }
        [Column("CDInventoryKirbysPercentCut", TypeName = "decimal(5,2)")]
        public decimal CDInventoryKirbysPercentCut { get; set; }
        public int LPInventoryQty { get; set; }
        [Column("LPInventoryCost", TypeName = "decimal(9,2)")]
        public decimal LPInventoryCost { get; set; }
        [Column("LPInventoryKirbysCut", TypeName = "decimal(9,2)")]
        public decimal LPInventoryKirbysCut { get; set; }
        [Column("LPInventoryKirbysPercentCut", TypeName = "decimal(5,2)")]
        public decimal LPInventoryKirbysPercentCut { get; set; }
        public int OtherInventoryQty { get; set; }
        [Column("OtherInventoryCost", TypeName = "decimal(9,2)")]
        public decimal OtherInventoryCost { get; set; }
        [Column("OtherInventoryKirbysCut", TypeName = "decimal(9,2)")]
        public decimal OtherInventoryKirbysCut { get; set; }
        [Column("OtherInventoryKirbysPercentCut", TypeName = "decimal(5,2)")]
        public decimal OtherInventoryKirbysPercentCut { get; set; }
        public int TotalInventoryQty { get; set; }
        [Column("TotalInventoryCost", TypeName = "decimal(9,2)")]
        public decimal TotalInventoryCost { get; set; }
        [Column("TotalInventoryKirbysCut", TypeName = "decimal(9,2)")]
        public decimal TotalInventoryKirbysCut { get; set; }
        [Column("TotalInventoryKirbysPercentCut", TypeName = "decimal(5,2)")]
        public decimal TotalInventoryKirbysPercentCut { get; set; }
        [Column("CD30Days_KirbysCut", TypeName = "decimal(9,2)")]
        public decimal CD30Days_KirbysCut { get; set; }
        [Column("CD30Days_Cost", TypeName = "decimal(9,2)")]
        public decimal CD30Days_Cost { get; set; }
        public int CD30Days_Quantity { get; set; }
        [Column("LP30Days_KirbysCut", TypeName = "decimal(9,2)")]
        public decimal LP30Days_KirbysCut { get; set; }
        [Column("LP30Days_Cost", TypeName = "decimal(9,2)")]
        public decimal LP30Days_Cost { get; set; }
        public int LP30Days_Quantity { get; set; }
        [Column("Other30Days_KirbysCut", TypeName = "decimal(9,2)")]
        public decimal Other30Days_KirbysCut { get; set; }
        [Column("Other30Days_Cost", TypeName = "decimal(9,2)")]
        public decimal Other30Days_Cost { get; set; }
        public int Other30Days_Quantity { get; set; }
        [Column("Total30Days_KirbysCut", TypeName = "decimal(9,2)")]
        public decimal Total30Days_KirbysCut { get; set; }
        [Column("Total30Days_Cost", TypeName = "decimal(9,2)")]
        public decimal Total30Days_Cost { get; set; }
        public int Total30Days_Quantity { get; set; }
        public int? SoldItemsDaysBehind { get; set; }
        public int SoldHistory_FSI { get; set; }
        [Column("CD30Days_KirbysCut_Intermusic_FSI", TypeName = "decimal(9,2)")]
        public decimal CD30Days_KirbysCut_Intermusic_FSI { get; set; }
        [Column("CD30Days_Cost_Intermusic_FSI", TypeName = "decimal(9,2)")]
        public decimal CD30Days_Cost_Intermusic_FSI { get; set; }
        public int CD30Days_Quantity_Intermusic_FSI { get; set; }
        [Column("LP30Days_KirbysCut_Intermusic_FSI", TypeName = "decimal(9,2)")]
        public decimal LP30Days_KirbysCut_Intermusic_FSI { get; set; }
        [Column("LP30Days_Cost_Intermusic_FSI", TypeName = "decimal(9,2)")]
        public decimal LP30Days_Cost_Intermusic_FSI { get; set; }
        public int LP30Days_Quantity_Intermusic_FSI { get; set; }
        [Column("Other30Days_KirbysCut_Intermusic_FSI", TypeName = "decimal(9,2)")]
        public decimal Other30Days_KirbysCut_Intermusic_FSI { get; set; }
        [Column("Other30Days_Cost_Intermusic_FSI", TypeName = "decimal(9,2)")]
        public decimal Other30Days_Cost_Intermusic_FSI { get; set; }
        public int Other30Days_Quantity_Intermusic_FSI { get; set; }
        [Column("Total30Days_KirbysCut_Intermusic_FSI", TypeName = "decimal(9,2)")]
        public decimal Total30Days_KirbysCut_Intermusic_FSI { get; set; }
        [Column("Total30Days_Cost_Intermusic_FSI", TypeName = "decimal(9,2)")]
        public decimal Total30Days_Cost_Intermusic_FSI { get; set; }
        public int Total30Days_Quantity_Intermusic_FSI { get; set; }
        [Column("CD30Days_KirbysCut_FSI", TypeName = "decimal(9,2)")]
        public decimal CD30Days_KirbysCut_FSI { get; set; }
        [Column("CD30Days_Cost_FSI", TypeName = "decimal(9,2)")]
        public decimal CD30Days_Cost_FSI { get; set; }
        public int CD30Days_Quantity_FSI { get; set; }
        [Column("LP30Days_KirbysCut_FSI", TypeName = "decimal(9,2)")]
        public decimal LP30Days_KirbysCut_FSI { get; set; }
        [Column("LP30Days_Cost_FSI", TypeName = "decimal(9,2)")]
        public decimal LP30Days_Cost_FSI { get; set; }
        public int LP30Days_Quantity_FSI { get; set; }
        [Column("Other30Days_KirbysCut_FSI", TypeName = "decimal(9,2)")]
        public decimal Other30Days_KirbysCut_FSI { get; set; }
        [Column("Other30Days_Cost_FSI", TypeName = "decimal(9,2)")]
        public decimal Other30Days_Cost_FSI { get; set; }
        public int Other30Days_Quantity_FSI { get; set; }
        [Column("Total30Days_KirbysCut_FSI", TypeName = "decimal(9,2)")]
        public decimal Total30Days_KirbysCut_FSI { get; set; }
        [Column("Total30Days_Cost_FSI", TypeName = "decimal(9,2)")]
        public decimal Total30Days_Cost_FSI { get; set; }
        public int Total30Days_Quantity_FSI { get; set; }
    }
}
