// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spSeeIfOrderNumberExistsResult
    {
        [StringLength(15)]
        public string OrderNumber { get; set; }
    }
}
