// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MillionsOfRecordsApp.Models
{
    public partial class spSync_IsINTERNETREGGAEMaintenanceOpenGetValueResult
    {
        [StringLength(50)]
        public string IsINTERNETREGGAEMaintenanceOpen { get; set; }
    }
}
