// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MillionsOfRecordsApp.Models;

[Index("Artist", "InventoryId", Name = "IX_ArtistInventoryID", IsUnique = true)]
[Index("Format", Name = "IX_Format")]
[Index("InStock", Name = "IX_InStock")]
[Index("InventoryId", Name = "IX_InventoryID")]
public partial class WebArtist
{
    [StringLength(255)]
    public string Artist { get; set; }

    [Column("InventoryID")]
    public int? InventoryId { get; set; }

    [StringLength(50)]
    public string Format { get; set; }

    [StringLength(1)]
    public string InStock { get; set; }

    [Key]
    [Column("counter")]
    public int Counter { get; set; }
}