// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MillionsOfRecordsApp.Models;

[Keyless]
[Table("WebCountryStateProvincesList")]
public partial class WebCountryStateProvincesList
{
    [StringLength(100)]
    public string Country { get; set; }

    [StringLength(100)]
    public string StateProvince { get; set; }

    [StringLength(50)]
    public string StateProvinceAbbreviation { get; set; }

    [Column("counter")]
    public int? Counter { get; set; }
}