// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MillionsOfRecordsApp.Models;

[Index("SalesLast30Days", Name = "IX_SalesLast30Days")]
[Index("Total", Name = "IX_Total")]
[Index("Word1", Name = "IX_Word1")]
[Index("Word10", Name = "IX_Word10")]
[Index("Word11", Name = "IX_Word11")]
[Index("Word12", Name = "IX_Word12")]
[Index("Word13", Name = "IX_Word13")]
[Index("Word14", Name = "IX_Word14")]
[Index("Word15", Name = "IX_Word15")]
[Index("Word16", Name = "IX_Word16")]
[Index("Word17", Name = "IX_Word17")]
[Index("Word18", Name = "IX_Word18")]
[Index("Word19", Name = "IX_Word19")]
[Index("Word2", Name = "IX_Word2")]
[Index("Word20", Name = "IX_Word20")]
[Index("Word3", Name = "IX_Word3")]
[Index("Word4", Name = "IX_Word4")]
[Index("Word5", Name = "IX_Word5")]
[Index("Word6", Name = "IX_Word6")]
[Index("Word7", Name = "IX_Word7")]
[Index("Word8", Name = "IX_Word8")]
[Index("Word9", Name = "IX_Word9")]
public partial class WebSearchSuggestion
{
    [Required]
    [StringLength(255)]
    public string Hint { get; set; }

    public int Total { get; set; }

    [Column("CD")]
    public int Cd { get; set; }

    public int Vinyl { get; set; }

    public int Other { get; set; }

    [Required]
    [StringLength(50)]
    public string SearchType { get; set; }

    [Key]
    [Column("counter")]
    public int Counter { get; set; }

    [StringLength(50)]
    public string Word1 { get; set; }

    [StringLength(50)]
    public string Word2 { get; set; }

    [StringLength(50)]
    public string Word3 { get; set; }

    [StringLength(50)]
    public string Word4 { get; set; }

    [StringLength(50)]
    public string Word5 { get; set; }

    [StringLength(50)]
    public string Word6 { get; set; }

    [StringLength(50)]
    public string Word7 { get; set; }

    [StringLength(50)]
    public string Word8 { get; set; }

    [StringLength(50)]
    public string Word9 { get; set; }

    [StringLength(50)]
    public string Word10 { get; set; }

    [StringLength(50)]
    public string Word11 { get; set; }

    [StringLength(50)]
    public string Word12 { get; set; }

    [StringLength(50)]
    public string Word13 { get; set; }

    [StringLength(50)]
    public string Word14 { get; set; }

    [StringLength(50)]
    public string Word15 { get; set; }

    [StringLength(50)]
    public string Word16 { get; set; }

    [StringLength(50)]
    public string Word17 { get; set; }

    [StringLength(50)]
    public string Word18 { get; set; }

    [StringLength(50)]
    public string Word19 { get; set; }

    [StringLength(50)]
    public string Word20 { get; set; }

    public int? SalesLast30Days { get; set; }

    [StringLength(50)]
    public string ScanPath { get; set; }

    public int SortOrder { get; set; }
}