// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using MillionsOfRecordsApp.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MillionsOfRecordsApp.Data
{
    public partial interface IReggaeDbContextProcedures
    {
        Task<int> AdjustCartAsync(int? iD, decimal? price, int? type, int? qty, string cartName, string iPAddress, string searchCriteriaStatisticsID, int? customerID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<CartNumberOfItemsResult>> CartNumberOfItemsAsync(string cartName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteBackordersAsync(string cartName, int? customerID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spAddRetailCartItemToWholesaleCartAsync(string cartName, int? itemID, int? quantity, decimal? wholesalePrice, string searchCriteriaStatisticsID, string iPAddress, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spCartPricesSalePricesTooResult>> spCartPricesSalePricesTooAsync(string nameOfCart, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spCheckForLPor12InchInCartResult>> spCheckForLPor12InchInCartAsync(string cartName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spCheckIfLogInEmailExistsResult>> spCheckIfLogInEmailExistsAsync(string logInEmail, int? counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spCheckLogInEmailExistsResult>> spCheckLogInEmailExistsAsync(string logInEmail, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spCheckLogInEmailExistsWholesaleResult>> spCheckLogInEmailExistsWholesaleAsync(string logInEmail, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDeleteCartAsync(string cartName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDeleteCartItemAsync(string cartName, int? itemID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDownloadOK_CartsAsync(string counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDownloadOK_Carts_DeletesAsync(string counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDownloadOK_CustomerEmailChangesAsync(string counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDownloadOK_CustomersAsync(string counter, string newCustomerID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDownloadOK_DeleteBackordersInStockNowAsync(string counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDownloadOK_Enter7InchAsync(string counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDownloadOK_EnterStockAsync(string counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDownloadOK_OrderCorrectionNotesAsync(string counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDownloadOK_OrdersAsync(string counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDownloadOK_PayFlowRequestsAsync(string counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDownloadOK_PayPalIPNsReceivedAsync(string counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDownloadOK_SignInLogAsync(string counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetAirMailLetterPostZoneResult>> spGetAirMailLetterPostZoneAsync(string country, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetAirParcelPostZoneResult>> spGetAirParcelPostZoneAsync(string country, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetCartItemsResult>> spGetCartItemsAsync(string cartName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetCartItemsForPurchaseResult>> spGetCartItemsForPurchaseAsync(string cartName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetCartTotalsRetailPriceResult>> spGetCartTotalsRetailPriceAsync(string cartName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetCartTotalsWholesalePriceResult>> spGetCartTotalsWholesalePriceAsync(string cartName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetCountOfWebCountryStateProvincesResult>> spGetCountOfWebCountryStateProvincesAsync(string country, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetCountryInfoFromCounterResult>> spGetCountryInfoFromCounterAsync(int? counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetCountryListResult>> spGetCountryListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetCountryListRowResult>> spGetCountryListRowAsync(string countryText, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetCustomerDetailsResult>> spGetCustomerDetailsAsync(string logInEmail, string password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetCustomerDetailsByServerCounterResult>> spGetCustomerDetailsByServerCounterAsync(int? counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetCustomerInvoicesResult>> spGetCustomerInvoicesAsync(int? customerServerCounter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetEmailFooterResult>> spGetEmailFooterAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetInventoryItemResult>> spGetInventoryItemAsync(int? iD, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetMinimumFlatShippngChargeResult>> spGetMinimumFlatShippngChargeAsync(string shippingMethodCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetOrderItemsResult>> spGetOrderItemsAsync(string orderNumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetOrdersByCustomerServerCounterResult>> spGetOrdersByCustomerServerCounterAsync(int? counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetOrdersRowResult>> spGetOrdersRowAsync(string orderNumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetPendingCustomerOrdersResult>> spGetPendingCustomerOrdersAsync(int? customerServerCounter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetShippingCutoffMinutesResult>> spGetShippingCutoffMinutesAsync(string shippingMethodCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetShippingMethodsRowResult>> spGetShippingMethodsRowAsync(string shippingMethodCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTermsOfSaleTypesRowResult>> spGetTermsOfSaleTypesRowAsync(int? type, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetWebCountryShippingZonesTRowResult>> spGetWebCountryShippingZonesTRowAsync(string country, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetWebCountryStateProvincesListResult>> spGetWebCountryStateProvincesListAsync(string country, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetWebCountryStateProvincesListRowResult>> spGetWebCountryStateProvincesListRowAsync(string country, string stateProvince, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetWebSHIPX_FedExGroundTimeInTransitRowResult>> spGetWebSHIPX_FedExGroundTimeInTransitRowAsync(string zipCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetWebSHIPX_MaxWeightOfBoxForPackingResult>> spGetWebSHIPX_MaxWeightOfBoxForPackingAsync(string cartName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetWebSHIPX_PackagingWeightResult>> spGetWebSHIPX_PackagingWeightAsync(decimal? weightInGrams, string cartName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetWebSHIPX_ShippingHolidaysOutboundRowResult>> spGetWebSHIPX_ShippingHolidaysOutboundRowAsync(DateTime? date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetWebSHIPX_ShippingMethodsRowResult>> spGetWebSHIPX_ShippingMethodsRowAsync(string shippingMethodCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetWebSHIPX_UPSTimeInTransitRowResult>> spGetWebSHIPX_UPSTimeInTransitRowAsync(string zipCode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetWeightOfProductResult>> spGetWeightOfProductAsync(string cartName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spInsertCustomerResult>> spInsertCustomerAsync(string priceGroup, string customerID, string fullName, string streetAddress1, string streetAddress2, string city, string stateProvince, string postalCode, string island, string country, string billingFullName, string billingStreetAddress1, string billingStreetAddress2, string billingCity, string billingStateProvince, string billingPostalCode, string billingIsland, string billingCountry, string phone, string phone2, string phone3, string email, string email2, string email3, string logInEmail, string password, string howFoundUs, string iPAddress, string residentialDelivery, string chargeSalesTax, OutputParameter<int?> iDOUTPUT, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spInsertCustomerCartsNotificationsAsync(int? customerServerCounter, DateTime? emailDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spInsertCustomerCartsNotificationsToSendResult>> spInsertCustomerCartsNotificationsToSendAsync(int? customerServerCounter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spInsertCustomerEmailChangesAsync(int? customerID, int? customerServerCounter, string oldEmail, string newEmail, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spInsertCustomerInteractionAsync(int? javascriptRandomNumber, string eBRep, string customerRep, string notes, int? customerID, string customerTableName, int? customerServerCounter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spInsertNewReleaseEmailOptInOrOutAsync(string password, string email, string fullName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spInsertStoreLogOnAccessedSuccessfulAsync(DateTime? dateTime, string iPAddress, string loggedOnSuccessful, string password, string logInEmail, string powerUserName, int? cartQuantity, string storename, string priceGroup, string city, int? customerServerCounter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spInsertStoreLogOnAccessedUnsuccessfulAsync(DateTime? dateTime, string iPAddress, string loggedOnSuccessful, string password, string logInEmail, string powerUserName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spInventoryItemFeaturesForListViewResult>> spInventoryItemFeaturesForListViewAsync(int? inventoryID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spInventoryItemFeaturesForProductDetailsPageResult>> spInventoryItemFeaturesForProductDetailsPageAsync(int? inventoryID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spOrderedQueriesAsync(string cartName1, string cartName2, int? customerServerCounter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spRecordPurchaseAsync(string logInEmail, string password, string priceGroup, string userAgent, decimal? weight, DateTime? dateTime, int? customerServerCounter, string changedAddress, string powerUserName, string remHost, string sessionID, string shippingMethod, string creditCardNumber, string expDate, decimal? creditCardAmountPaid, string pONumber, string printedInvoice, string email, string shippingMethodPullSheetText, string phone, string fullName, string streetAddress1, string streetAddress2, string city, string island, string stateProvince, string postalCode, string country, string billingFullName, string billingStreetAddress1, string billingStreetAddress2, string billingCity, string billingIsland, string billingStateProvince, string billingPostalCode, string billingCountry, string howFoundUs, string status, string orderNumber, string orderProcessChoice, string customerID, decimal? payPalAmountDue, decimal? googleCheckoutAmountDue, decimal? westernUnionAmountDue, decimal? checkCashorMoneyOrderAmountDue, string iPAddress, string orderNotes, decimal? shipping, decimal? tax, decimal? totalPrice, decimal? orderTotal, int? totalQuantity, decimal? giftCardAmount, string giftCardNumber, int? giftCardAccountsServerCounter, int? numberOfLineItems, string cartName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spResidentialDeliveryResult>> spResidentialDeliveryAsync(int? counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spSeeIfOrderNumberExistsResult>> spSeeIfOrderNumberExistsAsync(string orderNumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spUpdateCartQuantityInCustomersTableAsync(int? customerServerCounter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spUpdateCustomerDateOfLastLoginAsync(int? counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spUpdateCustomersAsync(string email, string phone, string residentialDelivery, string blockedFromCheckout, string chargeSalesTax, string priceGroup, string fullName, string streetAddress1, string streetAddress2, string city, string stateProvince, string postalCode, string island, string country, string billingFullName, string billingStreetAddress1, string billingStreetAddress2, string billingCity, string billingStateProvince, string billingPostalCode, string billingIsland, string billingCountry, string logInEmail, string password, int? counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spUpdateCustomerTotalSignInsAsync(int? counter, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spUpdateEmailedOrderConfirmationAsync(string orderNumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spUSPSNotShippingToResult>> spUSPSNotShippingToAsync(string country, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
