// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using MillionsOfRecordsApp.Models;

namespace MillionsOfRecordsApp.Data;

public partial class ReggaeDbContext : DbContext
{
    public ReggaeDbContext(DbContextOptions<ReggaeDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CountryList> CountryLists { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Inventory> Inventories { get; set; }

    public virtual DbSet<InventoryItemFeature> InventoryItemFeatures { get; set; }

    public virtual DbSet<InventoryItemFeatureIndex> InventoryItemFeatureIndices { get; set; }

    public virtual DbSet<WebArtist> WebArtists { get; set; }

    public virtual DbSet<WebCountryStateProvincesList> WebCountryStateProvincesLists { get; set; }

    public virtual DbSet<WebSearchSuggestion> WebSearchSuggestions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.Counter).IsClustered(false);

            entity.ToTable(tb =>
                {
                    tb.HasTrigger("Carts_DeleteTrigger");
                    tb.HasTrigger("Carts_UpdateTrigger");
                });

            entity.Property(e => e.DateTime).HasDefaultValueSql("(getdate())", "DF_Carts_DateTime");
            entity.Property(e => e.InSync)
                .IsFixedLength()
                .HasDefaultValue("n", "DF_Carts_InSync");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.ToTable(tb => tb.HasTrigger("Customers_UpdateTrigger"));

            entity.HasIndex(e => e.FullName, "IX_FullName").IsClustered();

            entity.Property(e => e.BlockedFromCheckout).HasDefaultValue("n", "DF_Customers_BlockedFromCheckout");
            entity.Property(e => e.Counter).ValueGeneratedOnAdd();
            entity.Property(e => e.CustomerId).HasDefaultValue("-", "DF_Customers_CustomerID");
            entity.Property(e => e.DateTime).IsFixedLength();
            entity.Property(e => e.InSync)
                .IsFixedLength()
                .HasDefaultValue("n", "DF_Customers_InSync");
            entity.Property(e => e.PriceGroup).HasDefaultValue("StorePrice", "DF_Customers_PriceGroup");
        });

        modelBuilder.Entity<Inventory>(entity =>
        {
            entity.ToTable("Inventory", tb =>
                {
                    tb.HasTrigger("Inventory_DeleteTrigger");
                    tb.HasTrigger("Inventory_InsertTrigger");
                    tb.HasTrigger("Inventory_UpdateTrigger");
                });
        });

        modelBuilder.Entity<InventoryItemFeature>(entity =>
        {
            entity.ToTable(tb =>
                {
                    tb.HasTrigger("InventoryItemFeatures_DeleteTrigger");
                    tb.HasTrigger("InventoryItemFeatures_InsertTrigger");
                    tb.HasTrigger("InventoryItemFeatures_UpdateTrigger");
                });
        });

        modelBuilder.Entity<InventoryItemFeatureIndex>(entity =>
        {
            entity.ToTable("InventoryItemFeatureIndex", tb =>
                {
                    tb.HasTrigger("InventoryItemFeatureIndex_DeleteTrigger");
                    tb.HasTrigger("InventoryItemFeatureIndex_InsertTrigger");
                    tb.HasTrigger("InventoryItemFeatureIndex_UpdateTrigger");
                });

            entity.Property(e => e.InventoryItemFeatureId).ValueGeneratedNever();
        });

        modelBuilder.Entity<WebArtist>(entity =>
        {
            entity.HasKey(e => e.Counter).IsClustered(false);

            entity.HasIndex(e => e.Artist, "IX_Artist").IsClustered();
        });

        modelBuilder.Entity<WebSearchSuggestion>(entity =>
        {
            entity.Property(e => e.SalesLast30Days).HasDefaultValue(0, "DF_WebSearchSuggestions_SalesLast30Days");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}